### ISSUE TITLE
Error when installing Torchcraft 

### ISSUE THREAD

**Issue by antonioLuis23** [TorchCraft/TorchCraft#253]
Hi guys, 

I am receiving this error when entering "luarocks make *.rockspec": 

Linking CXX shared library libtorchcraft.so
/usr/bin/ld: /usr/local/lib/libzstd.a(zstd_compress.o): relocation R_X86_64_PC32 against symbol `ZSTD_seqToCodes' can not be used when making a shared object; recompilar com -fPIC
/usr/bin/ld: falha no link final: Valor incorreto
collect2: error: ld returned 1 exit status
CMakeFiles/torchcraft.dir/build.make:253: recipe for target 'libtorchcraft.so.1.3.0' failed
make[2]: *** [libtorchcraft.so.1.3.0] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/torchcraft.dir/all' failed
make[1]: *** [CMakeFiles/torchcraft.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

Does anyone know a way around this? I am using Ubuntu 17.10, Torchcraft 1.3.0, and I tried with zstd 1.1.4 and 1.3.3

Thanks in advance.

**Comment by ebetica** [comment]
Can you try compiling zstd with the -fPIC option? For example, if you use cmake, you can pass in ` cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON .....`

**Comment by antonioLuis23** [comment]
Hey it works. Thanks Zeming!

**Comment by rocketfive** [comment]
> Hey it works. Thanks Zeming!

hello，guys，I meet almost same problem with you when I installing torchcraft. But I am curious about the solution that ebetica mentioned.
I have installed dependents and so on,then I enter command "luarocks make *.rockspec"  
but how to use the -fPIC with this command?  Can you give the exact command?

I'm a fresher, so it maybe a little silly. Thanks advance!

**Comment by ebetica** [comment]
This is about the zstd library installed in your system. This library needs to be compiled with -fPIC support. You can find the CMake instructions here: https://github.com/facebook/zstd/tree/dev/build/cmake

**Comment by rocketfive** [comment]
> This is about the zstd library installed in your system. This library needs to be compiled with -fPIC support. You can find the CMake instructions here: https://github.com/facebook/zstd/tree/dev/build/cmake

thanks a lot. Now I know that I need to compiled the library in the path  "zstd/build/cmake" . Then I enter the command "cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
it tells me that "Build files have been written to: /home/rocket/zstd/build/cmake"
after that , I enter "make" "make install"  then it tells me "zstd installation completed"

in the last , I went to path torchcraft and enter  "luarocks make *.rockspec" again, it still the same error:
[  4%] Linking CXX shared library libtorchcraft.so
/usr/bin/ld: /usr/local/lib/libzstd.a(zstd_common.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libzstd.a: 无法添加符号: 错误的值
collect2: error: ld returned 1 exit status
CMakeFiles/torchcraft.dir/build.make:329: recipe for target 'libtorchcraft.so.1.4.0' failed
make[2]: *** [libtorchcraft.so.1.4.0] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/torchcraft.dir/all' failed
make[1]: *** [CMakeFiles/torchcraft.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

where is the problem? If I need to do something to correct the zstd with torchcraft?
sincerely thanks again!

**Comment by rocketfive** [comment]
> 无法添加符号: 错误的值

无法添加符号: 错误的值 this means Unable to add symbol: error value in Chinese

**Comment by ebetica** [comment]
I suspect it is because it's still finding the system libzstd? Where was your compiled zstd installed to? Maybe you can try uninstall zstd from your package manager, or otherwise updating your LD_LIBRARY_PATH to point to the correct zstd.

**Comment by rocketfive** [comment]
thanks a lot. I'm sorry I don't check the email because I think you may reply on the git. I solve it by follow:
open the cmakelist.txt file in the torchcraft file folder, and then find the line which IF(ZSTD_FOUND) , add&nbsp;SET(CFLAGS += -fPIC)
and at last it should be like this:
IF(ZSTD_FOUND)
&nbsp; &nbsp; # Use the static library since we're using "advanced/experimental" features
&nbsp; &nbsp; TARGET_LINK_LIBRARIES(torchcraft ${ZSTD_LIBDIR}/libzstd.so)
&nbsp; &nbsp; SET(CFLAGS += -fPIC)
&nbsp; &nbsp; # TARGET_LINK_LIBRARIES(torchcraft ${ZSTD_LIBDIR}/libzstd.a)
ENDIF()



and it should be ok, but I am not sure why it can works&nbsp;


after all, thanks again




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeming Lin"<notifications@github.com&gt;; 
发送时间: 2020年3月24日(星期二) 凌晨4:14
收件人: "TorchCraft/TorchCraft"<TorchCraft@noreply.github.com&gt;; 
抄送: "长征五号甲"<526291598@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [TorchCraft/TorchCraft] Error when installing Torchcraft  (#253)





 
I suspect it is because it's still finding the system libzstd? Where was your compiled zstd installed to? Maybe you can try uninstall zstd from your package manager, or otherwise updating your LD_LIBRARY_PATH to point to the correct zstd.
