### ISSUE TITLE
Error while starting OpenBW

### ISSUE THREAD

**Issue by luanshaotong** [TorchCraft/TorchCraft#313]
I installed torchcraftAI according to
https://torchcraft.github.io/TorchCraftAI/docs/install-linux.html
But when I start openBW, there's an error.
![image](https://user-images.githubusercontent.com/14962503/65971575-f2bbc800-e49a-11e9-92b5-879bc8dd44dd.png)
Could you tell me how to run openBW?

**Comment by dgant** [comment]
It looks like OpenBW is trying to read one of the MPQ files -- which are archives like ZIPs containing multiple other files -- but not finding an expected file inside (staredit/scenario.chk).

You may want to verify that you have proper copies of the MPQ files, from a 1.16.1 StarCraft installation. I suspect, because it's specifically missing a staredit file, that you're using Remastered MPQs (since Remastered removed StarEdit).

**Comment by luanshaotong** [comment]
@dgant Oh, I used a DIY map to run OpenBW. Now the error disappears using micro-big.scm in /TorchcraftAI/test/maps/ . But a new issue appears.
![image](https://user-images.githubusercontent.com/14962503/66017327-e4a68f80-e50c-11e9-9b09-0b96cf31ea3f.png)

**Comment by luanshaotong** [comment]
@dgant Oh, I used a DIY map to run OpenBW. Now it works using micro-big.scm in TorchcraftAI/test/maps/ . Thanks~
